### ISSUE TITLE
Hardcoded image names/versions

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/binfinder#1]
Hi @rahul2393, I'm wondering why there are hardcoded image names and version numbers in the code [here, for elasticsearch and logstash](https://github.com/aquasecurity/binfinder/blob/92b85bf85537f3551943f6b29b16f998ccfa5593/main.go#L116). If this is really necessary please could you add a comment to explain it and why these two specific images are special cases?

**Comment by rahul2393** [comment]
@lizrice Issue is for non-registry images we can't pull valid tags like Elasticsearch and Logstash don't have the latest tags the CLI will break where we scraping popular images from Dockerhub explore page, so to make it work I hardcoded it.
For registry use cases this will not be executed, and never be used.

**Comment by lizrice** [comment]
Sorry, but this doesn't make sense to me. 
* What do you mean by "non-registry image"? Do you mean local images (currently residing on the local machine), or perhaps do you mean images stored on Docker Hub (where there is no registry specified, so it defaults to Docker Hub's URL `docker.io`)? 
* Why just these two images? Are there no other similar images? How do you plan to handle updates to the version number tags for these images and other similar ones?

**Comment by rahul2393** [comment]
@lizrice Anyways removed hardcoded tags 
https://github.com/aquasecurity/binfinder/commit/5b2447e25073b6c33218e0fc3ea922983647ea7a
Found API to get the recent tag from here 
https://hub.docker.com/v2/repositories/library/elasticsearch/tags?page=1&page_size=1
You can close now

**Comment by lizrice** [comment]
Thanks
