### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by simar7** [aquasecurity/binfinder#2]
At the time of filing this issue, I didn't find any unit tests. Stability aside, we won't be able to guarantee the program's correctness if logic gets refactored or changed in the future. It also helps someone like me who has never seen the repo before to understand the intentions behind the code.

Is that something you're looking into @rahul2393 at the moment?

**Comment by rahul2393** [comment]
@simar7 The priority was to hand over the working script to Amir at first, but yes we want to add the tests, help appreciated if you want to add some, I will later contribute too.
Thanks

**Comment by simar7** [comment]
I've added some to get us started. They are not purely unit tests so we will at some point need to stub out the external dependencies. Closing this for now.
