### ISSUE TITLE
binfinder fails to run 

### ISSUE THREAD

**Issue by simar7** [aquasecurity/binfinder#3]
```
➜  binfinder git:(master) ✗ ./binfinder --images    alpine:3.10.1
2020/09/01 15:13:43 topN value is 0, running binfinder on images passed by --images flag
Pulling image: alpine:3.10.1...
2020/09/01 15:13:44 exit status 1
➜  binfinder git:(master) ✗ echo $?
1
➜  binfinder git:(master) ✗ ./binfinder --images    alpine:3.10  
2020/09/01 15:13:54 topN value is 0, running binfinder on images passed by --images flag
Pulling image: alpine:3.10...
2020/09/01 15:13:55 exit status 1
```

What am I doing wrong?

**Comment by simar7** [comment]
Ah – it looks like it needs docker daemon to be up and running. Let's do the following:

1. Document this behaviour in the README
2. Handle it gracefully. Show a message to the user telling them they need docker daemon running before they can run binfinder.
3. Add a test for this use case.

**Comment by rahul2393** [comment]
@simar7 Updated Readme added test case and logging the error for the user to see if docker daemon running or not.
https://github.com/aquasecurity/binfinder
You can close this issue.
Thanks

**Comment by simar7** [comment]
lgtm
